### ISSUE TITLE
Missing an expected key "NSPrivacyCollectedDataTypes" in Privacyinfo.xcprivacy

### ISSUE THREAD

**Issue by tatsuz0u** [pointfreeco/swift-sharing#29]
### Description

When generating a privacy report for my project, an error is reported indicating that the `NSPrivacyCollectedDataTypes` key is missing in the `PrivacyInfo.xcprivacy` file of the `swift-sharing` package.

### Checklist

- [X] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-sharing/issues) or [discussion](https://github.com/pointfreeco/swift-sharing/discussions).

### Expected behavior

The generated privacy report should not contain any information about `swift-sharing` since it doesn't collect data.

### Actual behavior

The generated privacy report indicates that the expected key `NSPrivacyCollectedDataTypes` is missing in the `PrivacyInfo.xcprivacy` file of `swift-sharing`.

### Reproducing project

[Demo.zip](https://github.com/user-attachments/files/18070599/Demo.zip)
[Demo-PrivacyReport 2024-12-10 11-21-34.pdf](https://github.com/user-attachments/files/18070600/Demo-PrivacyReport.2024-12-10.11-21-34.pdf)

### Sharing version information

main branch 524e1a6, 1.0.2

### Xcode version information

16.1.0

### Swift Compiler version information

```shell
swift-driver version: 1.115 Apple Swift version 6.0.2 (swiftlang-6.0.2.1.2 clang-1600.0.26.4)
Target: arm64-apple-macosx15.0
```

**Comment by stephencelis** [comment]
@tatsuz0u Thanks for the report! Can you run things against this branch and report back if it fixes? https://github.com/pointfreeco/swift-sharing/pull/31

**Comment by tatsuz0u** [comment]
@stephencelis Thank you for the fix! I tested the changes on the main branch, and the key missing error is no longer occurring. 🥳
