### ISSUE TITLE
Is this lib missing a dependency on CombineSchedulers?

### ISSUE THREAD

**Issue by ryanmeisters** [pointfreeco/swift-sharing#32]
### Description

Howdy! We have a large project with tons of modules. When updating to TCA 1.17.0 I'm getting these linking errors when xcode tries to link Sharing:

```
Showing All Messages
Undefined symbol: CombineSchedulers.AnyScheduler.now.getter : A

Undefined symbol: static (extension in CombineSchedulers):CombineSchedulers.AnyScheduler< where A == (extension in Dispatch):__C.OS_dispatch_queue.SchedulerTimeType, B == (extension in Dispatch):__C.OS_dispatch_queue.SchedulerOptions>.immediate.getter : CombineSchedulers.AnyScheduler<(extension in Dispatch):__C.OS_dispatch_queue.SchedulerTimeType, (extension in Dispatch):__C.OS_dispatch_queue.SchedulerOptions>

Undefined symbol: type metadata accessor for CombineSchedulers.AnyScheduler

Undefined symbol: nominal type descriptor for CombineSchedulers.AnyScheduler

Undefined symbol: protocol conformance descriptor for CombineSchedulers.AnyScheduler<A, B> : Combine.Scheduler in CombineSchedulers

Linker command failed with exit code 1 (use -v to see invocation)
```

I'm wondering if Sharing is missing a dependency on CombineSchedulers, e.g. [this code here](https://github.com/pointfreeco/swift-sharing/blob/464a3292d4c9630d33b8a505e4bb058caf57b8fc/Sources/Sharing/SharedKeys/FileStorageKey.swift#L343) looks like `.immediate` comes from there? 

Our project is complex so this could be a me problem, but wanted to make sure i'm not crazy.

### Checklist

- [ ] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [ ] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-sharing/issues) or [discussion](https://github.com/pointfreeco/swift-sharing/discussions).

**Comment by stephencelis** [comment]
@ryanmeisters swift-sharing depends on swift-dependencies, which depends on combine-schedulers, so I don't think this is the problem you are seeing. I'm going to convert to a discussion till we can determine this is a bug in the library. Can you share a repro so we can see if this is something to do with your project vs. our library?
