### ISSUE TITLE
Hyperlinks 404

### ISSUE THREAD

**Issue by rehatkathuria** [pointfreeco/swift-sharing#5]
### Description

It looks like the URLs in the README are leading to pages that arent't found:

https://swiftpackageindex.com/pointfreeco/swift-sharing/main/documentation/sharing/persistencestrategies

### Checklist

- [ ] I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
- [ ] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-sharing/issues) or [discussion](https://github.com/pointfreeco/swift-sharing/discussions).

**Comment by mbrandonw** [comment]
We are still waiting for docs to be generated. I will be fixed eventually.
